### PR TITLE
updated compat for IntervalArithmetic

### PR DESCRIPTION
**Pull request by lucaferranti**
As IntervalArithmetic was updated to 0.18 recently, this pull request updates the compat entry in `Project.toml`.

Would you like me to add the CompatHelper.yml to the workflow? Once a day it checks the dependencies of the package and automatically opens a PR if some entries in compat should be updated.

### CODE REVIEW

**Comment by lbenet** [comment]
Thanks a lot!

Could you also update other entries: v0.11 for TaylorSeries.jl and v1.6 for julia, and perhaps leave v0.5 for InteravlRootFinding?

I guess it is a good idea to have CompatHelper.yml workflow, to simplify this maintenance.

**Comment by lbenet** [comment]
And sorry for the delay...

**Comment by lucaferranti** [comment]
done! I am not entirely sure about releases policy, is bumping the patch enough in this case?

**Review by lbenet — APPROVED** [review]
Thanks a lot! LGTM!

**Comment by lbenet** [comment]
I think a patch version is fine now! Thanks again a lot! I'm merging and then I'll register the new patch version

**Pull request merged**
