### PR TITLE
Solve failing tests (validated_integ.jl)

### PR DESCRIPTION
**Pull request by lbenet**
See [this comment](https://github.com/JuliaIntervals/TaylorModels.jl/pull/125#issuecomment-949675468) for the problem.

### CODE REVIEW

**Comment by lucaferranti** [comment]
huups, apologies for not noticing you tagged me. Anyway, I agree with Christian that it may make sense to update the compatibilities with IA and Julia. The documentation check seems to fail, but it seems to be unrelated to this PR

**Comment by lbenet** [comment]
@lucaferranti Thanks for the comment; do you understand the problem with the docs? Locally, I can't reproduce it.

**Comment by schillic** [comment]
Have you tried retriggering? It could just be a random failure.

**Comment by lucaferranti** [comment]
it was a plotting related issue, when Plots.jl is used with the GR backend, then it requires the small trick of my latest commit, more details [here](https://discourse.julialang.org/t/generation-of-documentation-fails-qt-qpa-xcb-could-not-connect-to-display/60988).

I am not sure why this didn't come up before, probably because this PR added `Plots.jl` as deps in the docs Project.toml

**Comment by lbenet** [comment]
Thanks @lucaferranti for fixing this! So I'll merge and then tag the new version!

**Pull request merged**
