### PR TITLE
Update Project.toml

### PR DESCRIPTION
**Pull request by mforets**
see https://discourse.julialang.org/t/ann-releasing-recipesbase-1-0-and-plots-1-0-please-read/37056

### CODE REVIEW

**Comment by lbenet** [comment]
Thanks @mforets and sorry for the slow reply. To make effective this change, we should also tag a new version. Is this correct? If so, can you update the version in this PR.

**Comment by lbenet** [comment]
... and maybe allow also IntervalArithmetic version 0.17.0?

**Comment by mforets** [comment]
CI passed. It installed [IntervalArithmetic v0.16.1 though](https://travis-ci.org/github/JuliaIntervals/TaylorModels.jl/jobs/676203741#L150), so maybe there'r another downstream packages that needs to update the compat bound (?)

**Comment by lbenet** [comment]
Let me take a look on that...

**Comment by lbenet** [comment]
@mforets It seems the problem is related to IntervalRootFinding.jl; I am trying to fix that [here](https://github.com/JuliaIntervals/IntervalRootFinding.jl/pull/152), which would involve releasing a  patch version. I ping you when that is ready; I guess you will have to fix the package boundaries again.

**Comment by lbenet** [comment]
Registration of a new patch version of TaylorIntegration.jl is [on its way](https://github.com/JuliaRegistries/General/pull/13535).

**Comment by lbenet** [comment]
@mforets  IntervalRootFinding.jl v0.5.3 has been released; I think upgrading to that version solves the problem.

**Comment by mforets** [comment]
Awesome! I can confirm that the new IntervalArithmetic version is installed in the [automated tests](https://travis-ci.org/github/JuliaReach/LazySets.jl/jobs/679325654#L197).

**Comment by lbenet** [comment]
Merging. Thanks a lot @mforets  !

**Pull request merged**
