### PR TITLE
Add TM1 short-cut constructor expanding around midpoint

### LINKED ISSUE #20: Add a contractor expanding around midpoint by default
```
TaylorModel1(n, X) = TaylorModel1(n, interval(mid(X)), X)
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #20.

### CODE REVIEW

**Comment by lbenet** [comment]
Thanks a lot! LGTM. I am not sure if the failures in windows are related with https://github.com/JuliaDiff/TaylorSeries.jl/pull/189, which is now on master.

What about #22?

**Comment by lbenet** [comment]
@mforets Could you modify appveyor, dropping x86 tests, as suggested [here](https://github.com/JuliaIntervals/TaylorModels.jl/pull/18#issuecomment-459878530)?

@dpsanders Do you have any other suggestion?

**Comment by mforets** [comment]
Alright. Yesterday i rebased with master after the update with AppVeyor, same for #22. CI is green now 💚

**Comment by dpsanders** [comment]
Thanks a lot!

**Pull request merged**
