### PR TITLE
A new approach for the validated integration of ODEs

### PR DESCRIPTION
**Pull request by UzielLinares**

### CODE REVIEW

**Comment by UzielLinares** [comment]
The test for the `dx/dt=x^2` relies on the new method for`remainder_product` function from eeafb27. So, for now, that test will fail.

**Comment by lbenet** [comment]
Thanks for addressing this!

**Comment by lbenet** [comment]
Some tests, which are not currently passing, should be fixed by #91; you may need to rebase once it is merged.

**Comment by UzielLinares** [comment]
Great, I'll wait for it.

**Comment by lbenet** [comment]
@UzielLinares Can you rebase to current master? This should run the tests using GitHub actions, and (perhaps) solve the problems spotted by travis. (GH actions is much  faster than travis.)

**Review by lbenet — COMMENTED** [review]
I have made some comments in some parts to smooth what i think are some rough corners.

**Comment by lbenet** [comment]
Thanks for rebasing to master! There was a broken test (windows, 1.3) which i couldn't understand, so I rerun the tests and now they are passing.

**Comment by lbenet** [comment]
There are still some broken tests on  nightly (1.7.0-DEV)

**Comment by lbenet** [comment]
There seem to be some conflicts (in `tests/validated_integ.jl`); can you resolve them?

**Comment by lbenet** [comment]
Maybe duplicating the tests  (old a new methods are tested) is the best...

**Comment by lbenet** [comment]
There is one test that seems to be stuck...

**Comment by lbenet** [comment]
The tests pass, but there is something preventing a test to complete. I'll simply go ahead and merge this to have this functionality in master. We can finish whatever is left later in a different PR.

Thanks a lot @UzielLinares!!!

**Pull request merged**
