### PR TITLE
Set docs preview

### PR DESCRIPTION
**Pull request by mforets**
Address comment https://github.com/JuliaIntervals/TaylorModels.jl/pull/98#pullrequestreview-571678901, once this is merged I'll rebase my docs PRs.. But there is a Note in blue ("Pull requests made from forks will not have previews. ...") so it may not work in #98 and #99 because they are from a fork.

### CODE REVIEW

**Comment by mforets** [comment]
the error on some travis builds seems unrelated

**Comment by mforets** [comment]
@lbenet could you try to re-trigger the Travis build?

**Comment by lbenet** [comment]
I've restarted the  travis build (on those jobs that didn't pass only).

**Comment by lbenet** [comment]
All tests are passing (except some in nightly, which I think is related to printing, so irrelevant). Shall I go  ahead and merge?

**Comment by lbenet** [comment]
Merging...

**Pull request merged**
