### PR TITLE
Drop support to Julia 0.7, add Project.toml and delete REQUIRE files

### PR DESCRIPTION
**Pull request by mforets**
This cherry-picks 2497729 from `lb/shrinkwrap`.

### CODE REVIEW

**Comment by lbenet** [comment]
Thanks a lot, this is something pending. 

I have one comment/question: should we use v0.5.0 of `TaylorIntegration.jl`, or rather v0.4.1. If we use v0.5.0, the current implementation of `validated_integ` will be broken. The fixes are simple and easy to implement though. I just want to make this explicit.

**Comment by mforets** [comment]
Then i suggest to restrict to `v0.4.1` here and register TaylorModels with JuliaRegistrator. I can handle the update of `validated_integ` in another PR.

**Comment by lbenet** [comment]
@mforets I agree, let's do it that way.

@dpsanders Do we have installed [Registrator]( https://github.com/JuliaComputing/Registrator.jl) and [TagBot](https://github.com/apps/julia-tagbot) for `TaylorModels.jl`?

**Comment by dpsanders** [comment]
Yes I think they're installed on all repos in JuliaIntervals.

**Comment by lbenet** [comment]
Excellent, so we wait for @mforets change in the version of TaylorIntegration, and then I'll tag a new version (v0.1.1).

**Comment by mforets** [comment]
`≤` [doesn't seem to be supported](https://docs.julialang.org/en/v1.0/stdlib/Pkg/#Inequality-specifiers-1), so i changed it to `<`.

**Comment by lbenet** [comment]
What about using `^`? E.g. `TaylorIntegration = "^ 0.4.1"`, or `TaylorIntegration = "^ 0.4"`

**Comment by mforets** [comment]
Ok, that one should correspond to `[0.4.1, 0.5.0)`.

**Comment by lbenet** [comment]
I agree. Let's wait for travis, and then I'll merge, and tag the new version.

**Comment by lbenet** [comment]
Thanks a lot @mforets!

**Pull request merged**
